GET http://localhost:3003/api/blogs

###
PUT http://localhost:3003/api/blogs/661bcfb331e381dce418d77a
Content-Type: application/json

{
  "title": "Updated title",
  "author": "Updated author",
  "url": "Updated url",
  "likes": 100
}